//
//  LocalizationExpectations.swift
//  BitcoinBlockExplorerUITests
//
//  GENERATED from BitcoinBlockExplorer/Utils/Localizable.xcstrings.
//  Single source of truth for the localization UI tests: each entry is the
//  exact string the catalog resolves to for that language. If you change a
//  translation in the catalog, regenerate this file (see UITests README).
//

enum LocalizationExpectations {

    /// Languages exercised by the localization UI tests (the `-AppleLanguages`
    /// value forced at launch).
    static let languages = ["en", "pt-BR", "es", "es-419", "de", "fr", "ru", "zh-Hans"]

    /// [language: [catalogKey: expectedDisplayedString]]
    static let strings: [String: [String: String]] = [
        "en": [
            "blockchain": "Blockchain",
            "calculator": "Calculator",
            "configuracoes": "Settings",
            "support": "Support",
            "sourceCode": "Source Code",
            "reportIssues": "Report issues",
            "privacyLabel": "Privacy Policy",
            "termsLabel": "Terms of use",
            "currencyLabel": "Currency",
            "informativeLabel": "Fee price estimation is based on an average native 140 vByte segwit transaction",
            "searchPlaceholder": "Block, hash, transaction or address",
            "searchGuideHeader": "You can search for",
            "searchGuideBlockHeightTitle": "Block height",
            "searchGuideBlockHashTitle": "Block hash",
            "searchGuideAddressTitle": "Bitcoin address",
            "searchGuideTransactionTitle": "Transaction ID",
            "invalid": "Invalid input",
            "internetConnectionLabel": "Please, check your internet connection and refresh the app.",
            "proAccess": "Get Pro access and enjoy benefits!",
            "subscribe": "Subscribe",
        ],
        "pt-BR": [
            "blockchain": "Blockchain",
            "calculator": "Calculadora",
            "configuracoes": "Configurações",
            "support": "Suporte",
            "sourceCode": "Código Fonte",
            "reportIssues": "Reporte issues",
            "privacyLabel": "Política de Privacidade",
            "termsLabel": "Termos de uso",
            "currencyLabel": "Moeda",
            "informativeLabel": "A estimativa do preço da taxa é baseada em uma transação segwit nativa média de 140 vByte",
            "searchPlaceholder": "Bloco, hash, transação ou endereço",
            "searchGuideHeader": "Você pode pesquisar por",
            "searchGuideBlockHeightTitle": "Altura do bloco",
            "searchGuideBlockHashTitle": "Hash do bloco",
            "searchGuideAddressTitle": "Endereço Bitcoin",
            "searchGuideTransactionTitle": "ID da transação",
            "invalid": "Entrada inválida",
            "internetConnectionLabel": "Verifique sua conexão a internet e recarregue o aplicativo.",
            "proAccess": "Obtenha acesso Pro e tenha vantagens!",
            "subscribe": "Assinar",
        ],
        "es": [
            "blockchain": "Blockchain",
            "calculator": "Calculadora",
            "configuracoes": "Ajustes",
            "support": "Soporte",
            "sourceCode": "Código Fuente",
            "reportIssues": "Informar de problemas",
            "privacyLabel": "Política de privacidad",
            "termsLabel": "Términos de uso",
            "currencyLabel": "Divisa",
            "informativeLabel": "La estimación del precio de la tarifa se basa en una transacción segwit nativa promedio de 140 vByte",
            "searchPlaceholder": "Bloqueo, hash, transacción o dirección",
            "searchGuideHeader": "Puedes buscar por",
            "searchGuideBlockHeightTitle": "Altura del bloque",
            "searchGuideBlockHashTitle": "Hash del bloque",
            "searchGuideAddressTitle": "Dirección Bitcoin",
            "searchGuideTransactionTitle": "ID de la transacción",
            "invalid": "Entrada no válida",
            "internetConnectionLabel": "Por favor, verifique su conexión a Internet y actualice la aplicación.",
            "proAccess": "¡Obtén acceso Pro y disfruta de beneficios!",
            "subscribe": "Suscribirse",
        ],
        "es-419": [
            "blockchain": "Blockchain",
            "calculator": "Calculadora",
            "configuracoes": "Ajustes",
            "support": "Soporte",
            "sourceCode": "Código Fuente",
            "reportIssues": "Informar de problemas",
            "privacyLabel": "Política de privacidad",
            "termsLabel": "Términos de uso",
            "currencyLabel": "Divisa",
            "informativeLabel": "La estimación del precio de la tarifa se basa en una transacción segwit nativa promedio de 140 vByte",
            "searchPlaceholder": "Bloqueo, hash, transacción o dirección",
            "searchGuideHeader": "Puedes buscar por",
            "searchGuideBlockHeightTitle": "Altura del bloque",
            "searchGuideBlockHashTitle": "Hash del bloque",
            "searchGuideAddressTitle": "Dirección Bitcoin",
            "searchGuideTransactionTitle": "ID de la transacción",
            "invalid": "Entrada no válida",
            "internetConnectionLabel": "Por favor, verifique su conexión a Internet y actualice la aplicación.",
            "proAccess": "¡Obtén acceso Pro y disfruta de beneficios!",
            "subscribe": "Suscribirse",
        ],
        "de": [
            "blockchain": "Blockchain",
            "calculator": "Kalkulator",
            "configuracoes": "Einstellungen",
            "support": "Unterstützung",
            "sourceCode": "Quellcode",
            "reportIssues": "Probleme melden",
            "privacyLabel": "Datenschutzerklärung",
            "termsLabel": "Nutzungsbedingungen",
            "currencyLabel": "Währung",
            "informativeLabel": "Die Gebührenschätzung basiert auf einer durchschnittlichen nativen SegWit-Transaktion von 140 vByte",
            "searchPlaceholder": "Block, Hash, Transaktion oder Adresse",
            "searchGuideHeader": "Du kannst suchen nach",
            "searchGuideBlockHeightTitle": "Blockhöhe",
            "searchGuideBlockHashTitle": "Block-Hash",
            "searchGuideAddressTitle": "Bitcoin-Adresse",
            "searchGuideTransactionTitle": "Transaktions-ID",
            "invalid": "Ungültige Eingabe",
            "internetConnectionLabel": "Bitte überprüfen Sie Ihre Internetverbindung und aktualisieren Sie die App.",
            "proAccess": "Holen Sie sich Pro-Zugang und genießen Sie die Vorteile!",
            "subscribe": "Abonnieren",
        ],
        "fr": [
            "blockchain": "Blockchain",
            "calculator": "Calculatrice",
            "configuracoes": "Paramètres",
            "support": "Soutien",
            "sourceCode": "Code source",
            "reportIssues": "Signaler des problèmes",
            "privacyLabel": "politique de confidentialité",
            "termsLabel": "Conditions d'utilisation",
            "currencyLabel": "Devise",
            "informativeLabel": "L'estimation du prix des frais est basée sur une transaction segwit native moyenne de 140 vByte",
            "searchPlaceholder": "Bloc, hachage, transaction ou adresse",
            "searchGuideHeader": "Vous pouvez rechercher",
            "searchGuideBlockHeightTitle": "Hauteur du bloc",
            "searchGuideBlockHashTitle": "Hachage du bloc",
            "searchGuideAddressTitle": "Adresse Bitcoin",
            "searchGuideTransactionTitle": "ID de transaction",
            "invalid": "Entrée invalide",
            "internetConnectionLabel": "Veuillez vérifier votre connexion Internet et actualiser l'application.",
            "proAccess": "Obtenez un accès Pro et profitez d'avantages!",
            "subscribe": "S'abonner",
        ],
        "ru": [
            "blockchain": "Блокчейн",
            "calculator": "Калькулятор",
            "configuracoes": "Настройки",
            "support": "Поддержка",
            "sourceCode": "исходный код",
            "reportIssues": "Сообщать о проблемах",
            "privacyLabel": "политика конфиденциальности",
            "termsLabel": "Условия использования",
            "currencyLabel": "Валюта",
            "informativeLabel": "Оценка бесплатной цены основана на средней собственной транзакции segwit объемом 140 байт",
            "searchPlaceholder": "Блок, хэш, транзакция или адрес",
            "searchGuideHeader": "Вы можете искать",
            "searchGuideBlockHeightTitle": "Высота блока",
            "searchGuideBlockHashTitle": "Хеш блока",
            "searchGuideAddressTitle": "Биткоин-адрес",
            "searchGuideTransactionTitle": "ID транзакции",
            "invalid": "Неверный ввод",
            "internetConnectionLabel": "Пожалуйста, проверьте свое интернет-соединение и обновите приложение.",
            "proAccess": "Получите профессиональный доступ и наслаждайтесь преимуществами!",
            "subscribe": "Подписываться",
        ],
        "zh-Hans": [
            "blockchain": "区块链",
            "calculator": "计算器",
            "configuracoes": "设置",
            "support": "支持",
            "sourceCode": "源代码",
            "reportIssues": "报告问题",
            "privacyLabel": "私隐政策",
            "termsLabel": "使用条款",
            "currencyLabel": "货币",
            "informativeLabel": "免费价格估算基于平均140字节segwit交易",
            "searchPlaceholder": "区块、哈希、交易或地址",
            "searchGuideHeader": "您可以搜索",
            "searchGuideBlockHeightTitle": "区块高度",
            "searchGuideBlockHashTitle": "区块哈希",
            "searchGuideAddressTitle": "比特币地址",
            "searchGuideTransactionTitle": "交易 ID",
            "invalid": "输入无效",
            "internetConnectionLabel": "请检查您的互联网连接并刷新应用程序.",
            "proAccess": "获得专业访问和享受好处!",
            "subscribe": "订阅",
        ],
    ]

    static func expected(_ key: String, language: String) -> String {
        strings[language]?[key] ?? strings["en"]?[key] ?? key
    }
}
